var inputExcel = {
    "CreateButton": "Création",
    "provisioning.cancelBackupRestoreStatusMessage ": "Chargement annulé.",
    "provisioning.restoreMessage": "Paramètres restaurés avec succès.",
    "navigation.tree.homepage_label_eco": " Page d'accueil",
    "navigation.tree.homepage_label_sce": "Page d'accueil",
    "navigation.tree.homepage_label_unknown": "Page d'accueil",
    "navigation.tree.bacnetGateway_label": "Passerelle BACnet",
    "navigation.tree.systemUtilities_label": "Utilitaires du système",
    "navigation.tree.backupRestore_label": "Sauvegarder la restauration",
    "navigation.tree.unitSettings_label": "Paramètres de l'unité",
    "diagnostics_buttonText": "Télécharger",
    "diagnostics_hasFiles": "Cette fonction est uniquement disponible pour l'assistance produit. Pour télécharger des informations de diagnostic pour la passerelle intelligente Hitachi, sélectionnez le bouton ci-dessous pour commencer le transfert de fichier.",
    "diagnostics_noFiles": "Cette fonction est uniquement disponible pour l'assistance produit. Aucune information de diagnostic n'est actuellement disponible pour la passerelle intelligente Hitachi.",
    "routes.unitSettings_title": "Paramètres de l'unité",
    "routes.bacnetGateway_title": "Passerelle BACnet",
    "routes.systemUtilities_title": "Utilitaires du système",
    "routes.backupRestore_title": "Sauvegarder la restauration",
    "vrf_gateway": "Passerelle VRF",
    "noScreen": "Cette page n'existe pas ou vous n'êtes pas autorisé à l'afficher.",
    "edit_device": "Modifier les détails de l'appareil",
    "save_device_details": "Enregistrer les détails de l'appareil",
    "unitNO_label": "Numéro d'unité",
    "model_label": "Modèle",
    "noHomepageNoCCT": "L'appareil ne prend pas en charge de page d'accueil. Veuillez sélectionner un élément dans le menu de navigation.",
    "mapHomepage": "La passerelle intelligente Hitachi n'est pas configurée pour afficher une quelconque information sur cette page. Sélectionnez l'élément de menu État pour afficher les informations de diagnostic de la passerelle intelligente Hitachi.",
    "backup_label": "Création Sauvegarde",
    "available_backup": "Sauvegarde disponible",
    "restore_label": "Restauration Sauvegarde",
    "unsupportedbrowser_message1": "Votre navigateur actuel n'est pas supporté.",
    "unsupportedbrowser_message2": "Veuillez utiliser un navigateur supporté pour mettre votre logiciel à jour.",
    "note_label": "Remarque",
    "upload_button": "Choisir le fichier",
    "update_label": "Mettre à jour",
    "stop_label": "Arrêt",
    "install_title": "Si vous cliquez sur Installer",
    "install_item1": "Tous les utilisateurs connectés seront déconnectés.",
    "install_item2": "La passerelle intelligente Hitachi ne sera pas disponible pendant 5 à 10 minutes.",
    "installnote_item1": "Ne débranchez pas l'alimentation.",
    "installnote_item2": "Votre appareil peut se connecter à un autre réseau Wi-Fi.",
    "installnote_item3": "Installation d'une version antérieure non autorisé. Un fichier d'une version antérieure sera considéré non valide.",
    "upload_label": "Lecture",
    "deviceList_errorSaving": "Erreur lors de l'enregistrement des détails de l'appareil",
    "deviceList_name_required": "Le nom ne peut pas être vierge.",
    "deviceList_description_required": "La description ne peut pas être vierge.",
    "deviceList_name_maxLength": "Le nom ne peut pas contenir plus de 30 caractères",
    "deviceList_description_maxLength": "La description ne peut pas contenir plus de 30 caractères",
    "error_invalidFilename": "Le nom du fichier doit comporter l'extension .dat, ou .back",
    "unitSettings_saveSuccess": "Modifications enregistrées",
    "unitSettings_unit": "Unité",
    "unitSettings_saveConfirmationMessage": "La modification des paramètres de l'unité de la passerelle intelligente Hitachi peut nécessiter une reconnexion au réseau.\n\nSouhaitez-vous vraiment continuer ?",
    "unitSettings_unitValidation": "Le champ Unité ne peut pas être vierge.",
    "unitSettings_caption": "Sélectionnez une unité",
    "unitsettings_errorLoading": "Erreur lors du chargement des paramètres de l'unité",
    "backup_restore_backup_filename": "Nom de la sauvegarde",
    "unitsettings_errorSaving": "Erreur lors de l'enregistrement des paramètres de l'unité",
    "backup_restore_note": "Remarque : veuillez saisir le nom du fichier de sauvegarde et appuyez sur le bouton « Créer »",
    "backup_restore_saveSuccess": "Modifications enregistrées",
    "backup_restore_errorSaving": "Erreur lors de l'enregistrement du fichier de sauvegarde",
    "wificlient_userpassword_label": "Mot de passe",
    "wificlient.deviceCommunicationError ": "Erreur : Il s'est produit une erreur de communication avec l'appareil sur lequel le fichier était en cours de lecture. (%s)",
    "wificlient_username_label": "Nom d'utilisateur",
    "wificlient.certificateValidationError ": "Il s'est produit une erreur de validation du package de mise à jour du logiciel pour l'installation. (%s : %s)",
    "wificlient.certificateUploadError": "Il s'est produit une erreur de lecture du package de mise à jour du logiciel. (%s : %s)",
    "wificlient.certificateUpdateError": "Erreur de mise à jour du logiciel (%s)",
    "wificlient_saveSuccess": "Modifications enregistrées",
    "wificlient_certificate_label": "Certificat CA",
    "wificlient_client_certificate_label": "Certificat du client",
    "wificlient_private_key_label": "Clé privée",
    "wificlient_private_key_passwd_label": "Mot de passe de la clé privée",
    "wificlient_identity_label": "Identité",
    "wificlient_authentication_status_label": "Etat d'authentification",
    "wificlient_connection_status_label": "Etat connexion",
    "wificlient_saveInProgress": "Enregistrement des paramètres du client Wifi. Cela peut prendre quelques minutes.",
    "devicesettings_deviceName.fields.invalidDeviceName": "Le nom de l'appareil ne peut pas contenir d'espace.",
    "routes.deviceSettings_title": "Paramètres de l'appareil",
    "deviceList_unit_number_required": "Le numéro de l'unité doit être renseigné.",
    "deviceList_unit_number_maxLength": "Le numéro de l'unité ne peut pas contenir plus de 30 caractères",
    "deviceSettings_saveSuccess": "Modifications enregistrées",
    "devicesettings_deviceName": "Nom d'appareil",
    "devicesettings_deviceID": "ID appareil",
    "devicesettings_bacnetIPNetworkAddress": "Adresse IP Réseau BACnet",
    "devicesettings_bacnetIPPort": "Port IP BACnet",
    "devicesettings_deviceName.fields.deviceNamemaxlength": "Le nom de l'appareil ne peut pas dépasser 32 caractères",
    "devicesettings_deviceName.fields.bacnetIPNetworkAddress_number_required": "L'adresse IP réseau BACnet ne doit contenir que des chiffres",
    "devicesettings_deviceName.fields.bacnetIPNetworkAddress_range_invalid": "La plage valide d'adresse IP réseau BACnet est comprise entre 1 et 65534",
    "devicesettings_deviceName.fields.deviceIDmaxlength": "L'ID de l'appareil ne peut pas dépasser 32 caractères",
    "devicesettings_saveConfirmationMessage": "Souhaitez-vous vraiment continuer?",
    "devicesettings_errorLoading": "Erreur lors du chargement des paramètres de l'unité",
    "devicesettings_errorSaving": "Erreur lors de l'enregistrement des paramètres de l'unité",
    "navigation.tree.deviceSettings_label": "Paramètres de l'appareil",
    "navigation.tree.bbmd_label": "BBMD",
    "bbmd.addnewentry_label": "Add",
    "bbmd.ipaddress_label": "Adresse IP",
    "bbmd.udpport_label": "Port du proxy",
    "bbmd.remove_label": "Supprimer",
    "bbmd.bbmd_saveSuccess": "Modifications enregistrées"
}